export const cardDetails = [{
    title: "New Customers",
    percentage: "58",
    count: 268,
    last: "Since last week",
    seriesCount: 58,
    strokeColor: "rgb(240, 80, 80)",
  },
  {
    title: "Online Orders",
    percentage: "80",
    count: 8715,
    last: "Since last month",
    seriesCount: 80,
    strokeColor: "rgb(103, 93, 183)",
  },
  {
    title: "Revenue",
    percentage: "77",
    count: "$925",
    last: "This week",
    seriesCount: 77,
    strokeColor: "rgb(35, 179, 151)",
  }, {
    title: "Daily Average",
    percentage: "35",
    count: "$78.83",
    last: "Revenue today",
    seriesCount: 35,
    strokeColor: "rgb(255, 189, 74)",
  }]